# Generated by Django 3.0.5 on 2020-04-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_future'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Future',
        ),
    ]
